services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_NAME=postgres
    depends_on:
      - postgres
      - redis
    command: >
      sh -c "python seed.py && flask run --host=0.0.0.0 --port=5000"
  # ... rest of the file remains the same

  celery:
    build: .
    command: celery -A app.celery worker --loglevel=info
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_NAME=postgres
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent volume for PostgreSQL

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  # Persistent volume for Redis

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin  # Persistent volume for PGAdmin

volumes:
  postgres_data:  # Volume for PostgreSQL data
  redis_data:     # Volume for Redis data
  pgadmin_data:   # Volume for PGAdmin data